export const INPUT_VALUEN_POPOXEL = 'INPUT_VALUEN_POPOXEL';
export const VALUEOV_FILTREL = 'VALUEOV_FILTREL';
export const TVYALNERI_POXANCUM = 'TVYALNERI_POXANCUM';
export const SORTAVOREL_YST = 'SORTAVOREL_YST';

export const SUBMIT_SEARCH_FORM = 'SUBMIT_SEARCH_FORM';
export const CHANGING_SEARCH_TEXT_VALUE = 'CHANGING_SEARCH_TEXT_VALUE';
export const CHANGING_SEARCH_BY_VALUE = 'CHANGING_SEARCH_BY_VALUE'; 
export const CHANGING_SORT_BY_VALUE = 'CHANGING_SORT_BY_VALUE'; 
